### ISSUE TITLE
Looks anything but art on windows

### ISSUE THREAD

**Issue by maraisr** [MonoLisaFont/feedback#37] opened 2020-08-21 00:42 UTC
Using 150 and otf

![image](https://user-images.githubusercontent.com/599459/90839316-8ee40b80-e39a-11ea-8fd6-f36e3491817a.png)

As you can see the font is being cut off on the top.

for comparison here is the same settings, but using DankMono.

![image](https://user-images.githubusercontent.com/599459/90839364-b33fe800-e39a-11ea-91e9-fe262dcf1dff.png)

I've tried the ttf, and otf.

Details:
- OS: Windows 10 Pro
- IDE: IntelliJ Webstorm 2020.2
- Settings:
- Enabled Font ligatures
- Size: 12, 1.1 spacing (higher spacing same diff)
- Subpixel ✅

**Comment by bebraw** [comment] 2020-08-21 07:03
@maraisr Can you re-download the font using the original download link at the email? I've included the current development build that **should** fix the issue. There are three builds in the zip now.

**Comment by bebraw** [comment] 2020-08-21 07:04
I'm closing this as a duplicate of #34.

@maraisr Let me know how it goes with the development build.

**Closed by bebraw** 2020-08-21 07:04 UTC

**Comment by maraisr** [comment] 2020-08-21 07:07
I've downloaded the `-dev` font, installed. 

Its definitely better. The `if` and `import` statements are still cut off. cc @bebraw 

![image](https://user-images.githubusercontent.com/599459/90862457-ca013180-e3d0-11ea-9dc3-6b08a75b8039.png)
