### ISSUE TITLE
vertical space between the two bars of `=>` ligature

### ISSUE THREAD

**Issue by yalelo** [MonoLisaFont/feedback#27] opened 2020-05-16 18:43 UTC
Hi,

I think the vertical space between the bars in ligatures like '=>'  is too narrow at small size (like 12px). Could be a hinting issue. But, I think it could be better to add some space between the bars to let them breath. 
What do you think ?

Thanks

**Comment by bebraw** [comment] 2020-06-15 10:05
@yalelo Can you provide more information? I'm mainly interested in the OS and the editor. A screenshot would help in debugging as well. Thanks!

**Comment by okonet** [comment] 2020-07-21 12:44
Duplicate of #19. Closing it. Let us know if it should be re-opened.

**Closed by okonet** 2020-07-21 12:44 UTC
Labels: bug, ligatures
