### ISSUE TITLE
Ligatures `>=` and `<=` are rendering too wide on Mac

### ISSUE THREAD

**Issue by josh-collinsworth** [MonoLisaFont/feedback#158] opened 2022-06-13 21:56 UTC
## Background information

* Font edition: Plus
* Font version: 1.808
* The type of the font file you are using: Tried both OTF and TTF
* Operating system: MacOS
* Display resolution: Both my 4K monitor and the built-in 13" retina display
* Any other information that might be helpful: See below

## Issue

For some reason, the `>=` and `<=` ligatures both render stretched at two characters wide, rather than a single character wide, anywhere I use them locally. 

Here's how it looks:
<img width="301" alt="13-53-zrjog-sflpc" src="https://user-images.githubusercontent.com/22334764/173451692-972315cd-850b-446d-8e57-3bdfc7d59d58.png">

And here's how it _should_ look (taken from CodePen):
<img width="280" alt="13-53-75b73-5i3xi" src="https://user-images.githubusercontent.com/22334764/173451709-567a948d-1c3e-4bca-96c8-14f2ac2b066b.png">

Some troubleshooting info that may be helpful:

- This happens regardless of the program in use on my machine: VS Code, iTerm, Font Book, and Affinity Designer all render the ligature incorrectly.
- This does _not_ seem to impact web fonts. I use MonoLisa on my personal website, and the ligatures render properly there, as well as on CodePen.
- This does _not_ happen with other coding fonts. (Or at least, not with Fira Code, which renders the same ligature at one character width.)
- This happens with both the OTF and the TTF files.

Thanks in advance for any help!

**Comment by bebraw** [comment] 2022-06-14 02:51
It's a known issue and this will be changed in the next release.

**Comment by freyjasasi** [comment] 2022-07-17 15:38
It's same in windows 11 also. When will be the next release?

**Comment by zhimoe** [comment] 2022-08-17 02:59
still too wide in 2.0 prerelease version ttf  
variable version is rigt, but jetbrains ide cannot use variable font

**Comment by bebraw** [comment] 2022-08-20 03:59
@zhimoe Can you download the prerelease again? I updated the version that has separate files in it. Earlier it was using some older version as I didn't have the right build available.

**Comment by bebraw** [comment] 2022-08-20 04:00
I'm closing this as a duplicate of #141.

In any case, the issue should be fixed in the prerelease

**Closed by bebraw** 2022-08-20 04:00 UTC
