### ISSUE TITLE
Cursive hyphen too wide when ligatures are disabled

### ISSUE THREAD

**Issue by konrad-straube** [MonoLisaFont/feedback#156] opened 2022-06-10 16:40 UTC
## Background information

* Font edition (i.e. trial, personal, plus, pro): personal
* Font version (i.e. 1.805): 1.808
* The type of the font file you are using (i.e. otf, ttf): otf
* Operating system (i.e. MacOS, Windows): Windows
* Display resolution (i.e. 3072x1920): 1080p

## Issue

VS Code allows you to disable ligatures by putting `"editor.fontLigatures": false,` in `settings.json`. So I have ligatures disabled, however, the minus/hyphen character (-) is too wide when cursive while ligatures are disabled (but looks normal with them enabled). I didn't see any other characters that were too wide but I haven't tested many. I only tested VS Code.

**Ligatures off**
![image](https://user-images.githubusercontent.com/74369576/173112169-ff38ea63-4bd3-4eaf-b656-d5398489b15d.png)

**Ligatures on** (no issue)
![image](https://user-images.githubusercontent.com/74369576/173112266-edff0dac-884b-4b4a-91a9-d664d649c2e3.png)

Best regards
Konrad

**Comment by bebraw** [comment] 2022-06-10 17:29
I think this might be a duplicate of #152 so it will be fixed in the next release.

**Comment by bebraw** [comment] 2022-08-20 04:03
This has been fixed in 2.0 prerelease.

**Closed by bebraw** 2022-08-20 04:03 UTC
Labels: bug
