### ISSUE TITLE
[Bug]: Customizing v2.010 does not display Plus features

### ISSUE THREAD

**Issue by siegblink** [MonoLisaFont/feedback#233] opened 2023-10-09 04:41 UTC
### Edition

Plus

### What version are you using?

v2.010

### What type of weights are you using?

Default (non-customized)

### Operating system

macOS Sonoma 14.0

### Program

VS Code

### Display resolution

3456 x 2234

### What happened?

I went to your website today to customize then download `v2.010` but I noticed that "Plus features" that I want to include is not being displayed in the UI. Here's a screenshot:

<img width="1728" alt="image" src="https://github.com/MonoLisaFont/feedback/assets/26909675/4769bc2a-f6dd-44f3-aa15-83324b4cdc99">

---

If I check the playground page, the plus features are there.

<img width="1728" alt="image" src="https://github.com/MonoLisaFont/feedback/assets/26909675/0bb74840-9e32-42ca-9382-b2f2619f8fda">

---

Below are the selections I made then I downloaded it.

<img width="1728" alt="image" src="https://github.com/MonoLisaFont/feedback/assets/26909675/2e031a5d-eff7-472d-acb1-de081f1c1725">

---

After installing the newly downloaded fonts, all the plus features I was hoping to get included are not there.

Not sure what's happening here or did I miss something?

**Comment by bebraw** [comment] 2023-10-09 04:49
Note that the selections should freeze the features directly to the font files.

@okonet Could this be related to the recent changes?

**Comment by bebraw** [comment] 2023-10-09 04:50
@siegblink Also note that you should **not** use the customize feature with VS Code since you can select the font features directly within it. Example: https://www.monolisa.dev/faq#how-to-enable-alternate-zero-stylistic-sets-and-the-script-variant .

**Comment by bebraw** [comment] 2023-10-09 04:51
https://www.monolisa.dev/faq#what-are-the-suggested-settings has the suggested settings for VS Code.

**Comment by siegblink** [comment] 2023-10-09 05:01
@bebraw I have no problem with VS Code, I'm good on that part.

I checked my Font Book app, the plus features such as the script variants and stuff are not there.

I reverted to v2.008 for now because v2.010 is broken for me.

**Comment by okonet** [comment] 2023-10-09 06:03
Just to clarify: is the issue with the website or with the font?

**Comment by bebraw** [comment] 2023-10-09 07:13
@siegblink You could try the following:

1. Download the font without touching a single feature switch
2. Open one of the downloaded ttfs at https://fontdrop.info/
3. It should show all the features

I tried this with Plus and it showed the features thay were expected. If even a single switch is enabled, it won't include the extra features.

**Comment by siegblink** [comment] 2023-10-09 09:16
@bebraw I followed your instructions.

Well, viewing newly downloaded MonoLisa font file without touching a single feature switch on [fontdrop.info ](https://fontdrop.info/) does display the plus features.

However, when you install the font file on your system, the issue still remains.

Thanks for the tip, though. But this is not the fix.

**Comment by siegblink** [comment] 2023-10-09 09:19
@okonet I believe it's the website that's causing all of this.

**Comment by bebraw** [comment] 2023-10-09 09:23
@siegblink Newly downloaded 2.010 works (no customization) works perfectly for me. To test, I tried toggling zero like this:

```json
{
  "editor.fontFamily": "MonoLisa",
  "editor.fontWeight": 400,
  "editor.fontLigatures": "'zero' off",
}
```

I think we would need VS Code font configuration to reproduce the issue since Fontdrop worked for you.

**Comment by siegblink** [comment] 2023-10-09 09:45
@bebraw I have no argument about MonoLisa v2.010 without customization. I have no trouble on this part.

What I'd really like to do is download v2.010 with customizations enabled and I don't know why I can't get those plus features.

Anyway, I'll roll back to `v2.008` for now. I appreciate your help.

**Comment by bebraw** [comment] 2023-10-09 09:48
@siegblink Ok, the customized version simply doesn't work with VS Code configuration since we strip the customized features and freeze them to the font.

It's possible there's some misunderstanding here and we don't know what to fix yet. Perhaps the UI could be more instructive as now the information is a bit hidden.

**Comment by egaban** [comment] 2023-10-10 13:26
Same issue here. Everything worked fine in previous releases, now every variation is shown as the same symbol

![image](https://github.com/MonoLisaFont/feedback/assets/18158965/25c48e80-f4fd-479b-be07-c8295c7bd4f9)

**Comment by bebraw** [comment] 2023-10-10 14:21
@egaban The UI should be fixed now.

**Comment by egaban** [comment] 2023-10-10 15:10
It's working now, thanks :)

**Comment by siegblink** [comment] 2023-10-10 16:03
Hey @bebraw 

I just went to the website and I can see the UI is now fixed.

I customized my selection with the plus features that I want then download it.

After installing, the plus features are now showing up.

I even patched the whole thing with Nerd font and it's still working properly.

Thanks for fixing this problem. Cheers!

**Closed as completed** 2023-10-10 16:04 UTC
Labels: bug
