### ISSUE TITLE
[Bug]: Variants do not get applied in ZIP download

### ISSUE THREAD

**Issue by TheoryOfNekomata** [MonoLisaFont/feedback#183] opened 2022-12-29 10:43 UTC
### Edition

Complete (Pro)

### What version are you using?

2.003

### What type of weights are you using?

Static (customized)

### Operating system

Windows 10

### What happened?

I've tried selecting the variants on the Orders page, but somehow the resulting ZIP file contains the TTF fonts without the selected variants applied (as if default values were selected).

Here are the options I've selected prior:

![image](https://user-images.githubusercontent.com/2346301/209940108-89b41a20-6687-492f-b3cc-7ab53127a537.png)

**Comment by bebraw** [comment] 2022-12-29 10:55
Did you use the download button at the top or the bottom (it's the bottom one to use)? Did it apply custom font name?

**Comment by TheoryOfNekomata** [comment] 2022-12-29 11:16
I clicked on the button at the bottom. At first, I didn't specify any prefix, which I got the ZIP file named `MonoLisa-Complete` with the default variants. Tried adding a prefix, which I got `MonoLisa-<prefix>`, with the same contents (different name in the font, but there isn't any hint of selected variants):

![image](https://user-images.githubusercontent.com/2346301/209943597-8998005a-21ce-4819-8a61-2bed88ca0d5c.png)

I remember downloading the font previously with variants applied--it should have the variants added in the font name:

![image](https://user-images.githubusercontent.com/2346301/209943452-e54b4d02-9097-4e05-bae7-6c19c0d1e663.png)

To be clear, should this second image be the intended behavior?

**Comment by bebraw** [comment] 2022-12-29 11:27
> To be clear, should this second image be the intended behavior?

This behavior changed a while ago and the first image is the expected result as it's following the suffix you gave.

Which editor are you using to test? Can you paste a screenshot from there with the customized font?

**Comment by TheoryOfNekomata** [comment] 2022-12-29 13:02
I'm currently using it in CLion:

![image](https://user-images.githubusercontent.com/2346301/209954408-e7884401-3b09-4e8d-a77c-006eebe9fbe0.png)

I am using the fonts I got directly from the site using the custom variants:

![image](https://user-images.githubusercontent.com/2346301/209954470-442957cf-4495-499d-b2be-3b30717ea3c4.png)

Here's the font preview if it helps:

![image](https://user-images.githubusercontent.com/2346301/209954598-099e55c0-2e65-4486-9760-b930afdd136f.png)

I was thinking if the rounded parenthesis prevents the other variants to be applied, because last time that option was disabled, iirc related to #179.

**Comment by bebraw** [comment] 2022-12-29 13:09
I think you might have to check that "Enable ligatures" checkbox. Can you try that?

**Comment by TheoryOfNekomata** [comment] 2022-12-29 13:57
Nothing happened 🤷 

![image](https://user-images.githubusercontent.com/2346301/209963660-c0d3e835-3b72-4928-a291-087b3f693fbc.png)

**Comment by bebraw** [comment] 2022-12-29 14:01
Ok, something feels off as even the zero in your screenshot wasn't frozen as I might expect. Maybe Andrey has a better idea of what's going on and I'm sure he'll comment on this thread when he has time.

Maybe there's some restriction in the way it applies changes that ligatures have to be enabled regardless for anything else to apply but that would feel weird. It's the only thing that comes to mind at this point.

**Comment by okonet** [comment] 2022-12-29 16:53
It’s a duplicate of #182 

See my explanation there: https://github.com/MonoLisaFont/feedback/issues/182#issuecomment-1364132974

**Comment by bebraw** [comment] 2022-12-29 16:54
Ah, ok. Let's close this one then.

**Closed by bebraw** 2022-12-29 16:54 UTC
Labels: bug
