### ISSUE TITLE
v 1.700 Bold and Bold Italic TTF thin font weights.

### ISSUE THREAD

**Issue by Pyre909** [MonoLisaFont/feedback#75] opened 2021-04-17 00:08 UTC
Hi,

Not sure if this is expected, but I'm noticing that when using the TTF font files the weight on bold regular and italic are looking thin. This does not happen on the OTF font files. 

Please see the attached screenshots.

<img width="1918" alt="font_preview" src="https://user-images.githubusercontent.com/3960786/115095443-92567500-9ede-11eb-8996-4439310051c6.PNG">
<img width="280" alt="notepad++_otf_fontdisplay" src="https://user-images.githubusercontent.com/3960786/115095444-92ef0b80-9ede-11eb-8a18-87073f830b13.PNG">
<img width="314" alt="notepad++_ttf_fontdisplay" src="https://user-images.githubusercontent.com/3960786/115095445-9387a200-9ede-11eb-94d1-ac5f25362548.PNG">
<img width="244" alt="vscode_otf_fontdisplay" src="https://user-images.githubusercontent.com/3960786/115095446-9387a200-9ede-11eb-97e0-a511ac732f43.PNG">
<img width="239" alt="vscode_ttf_fontdisplay" src="https://user-images.githubusercontent.com/3960786/115095447-9387a200-9ede-11eb-8a46-31d2e8a14771.PNG">

**Comment by Pyre909** [comment] 2021-04-17 00:09
oh Im on Windows 10 20h2 if that helps any.

**Comment by alexeyten** [comment] 2021-04-18 11:58
Same here. 1.7 is way too thin


1.7
![Terminal with MonoLisa 1.7](https://user-images.githubusercontent.com/44377/115144619-4f1f1200-a056-11eb-83b2-b37194b1a932.png)
1.602
![Terminal with MonoLisa 1.602](https://user-images.githubusercontent.com/44377/115144622-4fb7a880-a056-11eb-8dc2-72d3ce7aefeb.png)

**Comment by okonet** [comment] 2021-04-18 12:09
@mekkablue can you please take a look at this one? Seems like a regression.

**Comment by mekkablue** [comment] 2021-04-18 12:13
There was indeed an error in the first batch of TTF exports in 1.700 due to an incompatibility of software versions used.

The good news: This has been addressed already. New exports are in the 1.700/TTF folder.

**Comment by alexeyten** [comment] 2021-04-18 12:24
I've redownloaded archive.
It is good now.

**Comment by okonet** [comment] 2021-04-18 14:40
I’m closing this one. If you still experience it please re-download the font.

**Closed by okonet** 2021-04-18 14:40 UTC
Labels: bug
