### ISSUE TITLE
More symbol support, please 🙏

### ISSUE THREAD

**Issue by jjpiv-xerox** [MonoLisaFont/feedback#92] opened 2021-07-09 20:09 UTC
I just switched from Meslo LGS NF to MonoLisa and it would be excellent if there were parity with the symbols. For example, the Apple and folder symbols in the attached image.

![Screen Shot 2021-07-09 at 14 05 46](https://user-images.githubusercontent.com/76796019/125130763-c5b03680-e0be-11eb-999b-acea2fe92060.png)

**Comment by jjpiv-xerox** [comment] 2021-07-09 20:37
Closed because I found [https://github.com/MonoLisaFont/feedback/issues/57](Issue 57) addresses this enhancement request.

**Comment by okonet** [comment] 2021-07-11 10:31
I’m not sure: are we missing some glyphs in the font?

**Comment by jjpiv-xerox** [comment] 2021-07-12 19:19
Yeah, if Meslo LGS NF is selected in iTerm while using [Powerlevel10k](https://github.com/romkatv/powerlevel10k) the Apple logo and folder glyph are visible.
![Screen Shot 2021-07-12 at 13 15 20](https://user-images.githubusercontent.com/76796019/125343767-acec8e80-e313-11eb-9272-c98ffe72254f.png)
Whereas, if MonoLisa is chosen, the question mark boxes are shown.
![Screen Shot 2021-07-12 at 13 15 43](https://user-images.githubusercontent.com/76796019/125343784-b249d900-e313-11eb-8158-ef1048361554.png)

**Comment by okonet** [comment] 2021-07-13 05:48
@MarcusSterz can you please take a look?

**Comment by MarcusSterz** [comment] 2021-07-13 06:47
That’s not our notdef symbol so it seems the fallback font does not have the apple logo. Neither do we tbh. We will solve this with our next update.

**Comment by jjpiv-xerox** [comment] 2021-07-13 06:51
Excellent news, @MarcusSterz. Thanks to you and @okonet!

**Comment by bebraw** [comment] 2021-07-13 07:03
This is duplicate of #57 based on https://github.com/romkatv/powerlevel10k#fonts. To solve fully, Nerd Fonts compatibility would have to be achieved.

**Comment by jjpiv-xerox** [comment] 2021-07-13 07:07
@bebraw Is that likely to happen?

**Comment by bebraw** [comment] 2021-07-13 07:12
@jjpiv-xerox It's over 3000+ symbols to implement. Due to legal reasons, it's not clear if we can ship with a patched version out of the box. Adding all those would also bloat the size a lot (not good for web usage). For now, it's best to use their patching tool to apply the change. In #57 it's mentioned this should work.

**Comment by jjpiv-xerox** [comment] 2021-07-13 07:15
Thanks @bebraw 😊

**Comment by MarcusSterz** [comment] 2021-07-19 09:06
@bebraw @okonet So whats the conclusion? Shall we just implement the two bespoken symbols? If not what else?

**Comment by bebraw** [comment] 2021-07-19 09:28
@MarcusSterz Adding the two symbols wouldn't help as this is essentially about Nerd Fonts (#57) and there would be always more symbols missing (3000+ of them). I would close this issue as duplicate of that one.

**Closed** 2021-08-10 20:48 UTC
