### ISSUE TITLE
Font weight issue on 1.803

### ISSUE THREAD

**Issue by dongheeleeme** [MonoLisaFont/feedback#110] opened 2021-12-09 13:01 UTC
Hi, I just downloaded the latest version(1.803) and installed it on my machine. As we can see, It looks like the regular font is lighter than before. Would you please check on it? Thank you!

<img width="195" alt="Screenshot 2021-12-09 at 13 58 22" src="https://user-images.githubusercontent.com/38916112/145400761-72007151-2641-43bb-991b-eb89943ad0d2.png">
<img width="393" alt="Screenshot 2021-12-09 at 14 00 12" src="https://user-images.githubusercontent.com/38916112/145401025-dcea0739-be08-4a70-b764-4d35f69b4bfc.png">

**Comment by bebraw** [comment] 2021-12-09 14:03
Which version (otf, ttf) are you using?

**Comment by fabiochelly** [comment] 2021-12-09 14:19
I have the same problem (in IntelliJ) with the TTF version (IntelliJ doesn't recognize the OTF ones).

After update:
![after-update](https://user-images.githubusercontent.com/4060753/145413126-a33941f6-1fea-4156-bd46-c56bd2a4352e.png)

Before update:
![before-update](https://user-images.githubusercontent.com/4060753/145413135-f7df9c09-1f1f-458c-9d76-871cdd8af368.png)

**Comment by bebraw** [comment] 2021-12-09 14:30
It looks like the issue is limited to ttf. We'll do a small patch release tomorrow to amend this.

**Comment by bebraw** [comment] 2021-12-10 05:53
Fixed in 1.804 (available now).

**Closed by bebraw** 2021-12-10 05:53 UTC
Labels: bug, regression
