### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by vikky49** [MonoLisaFont/feedback#184] opened 2023-01-05 17:52 UTC
### Edition

Plus

### What version are you using?

2.003

### What type of weights are you using?

Default (non-customized)

### Operating system

Mac

### Program

iTerm2

### What happened?

This is how I configured my font with alt-g. 

<img width="573" alt="MonoLisa - My orders 2023-01-05 09-43-38" src="https://user-images.githubusercontent.com/180512/210846988-146bc4d3-4852-4bca-933b-9bcc3e2c30a6.png">

But it renders the default g in iTerm2. It used to work previously.

<img width="829" alt="pratyush@MacBook-Pro-3:~ 2023-01-05 09-47-26" src="https://user-images.githubusercontent.com/180512/210847128-ca0f3ef4-282f-41da-a243-0359048e9423.png">

It works fine in other editors. 

<img width="924" alt="portal – LearningSessionListServiceImpl java 2023-01-05 09-48-46" src="https://user-images.githubusercontent.com/180512/210847199-8186360e-a853-421a-bdf1-27ea4ad46a73.png">

This started happening very recently after your team enabled the "braces" and "brackets" replacement if that helps

**Comment by bebraw** [comment] 2023-01-05 19:07
I think this is a duplicate of #182. For this type of customization to work, `liga` has to be enabled at customizations. Unfortunately the UI doesn't communicate this at the moment. Better follow that issue for now.

**Comment by bebraw** [comment] 2023-01-05 19:08
Actually, let me leave this open for now so Andrey can confirm it's the same issue.

**Comment by bebraw** [comment] 2023-01-05 19:10
I think I get it now. Since it's about iTerm 2, did you enable ligatures at iTerm 2 settings? Now alternate g is coupled to that.

**Comment by okonet** [comment] 2023-01-05 19:26
Hmm it’s an interesting one. I think I’ll try to change the script so it works the same as before for non-ligatures. I’ll work on this next week probably. Thanks for reporting.

**Closed as completed** 2023-01-10 15:25 UTC
Labels: bug, customize
