### ISSUE TITLE
Ligature issue in Nova, VS Code, but not WebStorm

### ISSUE THREAD

**Issue by marktripney** [MonoLisaFont/feedback#138] opened 2022-03-24 08:37 UTC
## Background information

* Font edition (i.e. trial, personal, plus, pro): Personal
* Font version (i.e. 1.805): 1.808
* The type of the font file you are using (i.e. otf, ttf): otf
* Operating system (i.e. MacOS, Windows): Mac
* Display resolution (i.e. 3072x1920): 2560 x 1600
* Any other information that might be helpful: Issue persists across different editors and themes

## Issue

**Given this issue is not seen in WebStorm, this is perhaps more of a point of interest than an actual fault with the font.**

There seems to be a problem with the `#{` ligature — editors seem to be treating it as one character, leading to faulty syntax highlighting and mismatched braces. Not sure if this is an editor issue or something that could be addressed at font-level?

<img width="519" alt="Sass syntax-highlighting issue" src="https://user-images.githubusercontent.com/73220840/159871998-7fd3f253-a898-4636-9bda-c3b1640e30c9.png">

This is an example of Sass' interpolation syntax in Nova. The same issue is seen in VS Code. I've tried various themes in both editors and the issue persists. However... *WebStorm shows the correct behaviour* (below):

<img width="558" alt="Screenshot 2022-03-24 at 08 28 40" src="https://user-images.githubusercontent.com/73220840/159874392-9984a8ad-d3c4-476f-9be9-ef1306177208.png">

**Comment by bebraw** [comment] 2022-03-25 07:32
@marktripney Out of curiosity, can you check how it renders in Fira Code? They implement the same ligature so it would be interesting to know if they suffer from the same issue or if it's isolated.

**Comment by marktripney** [comment] 2022-03-25 07:50
@bebraw Interesting! Below, Fira Code (in Nova)...

<img width="520" alt="Screenshot 2022-03-25 at 07 43 35" src="https://user-images.githubusercontent.com/73220840/160076630-e37e22ad-82f2-4b09-8c3c-ce211bd4ea06.png">

... and, for comparison, MonoLisa:

<img width="525" alt="Screenshot 2022-03-25 at 07 46 10" src="https://user-images.githubusercontent.com/73220840/160076879-21c59e4c-ecf5-4222-af66-efa4fefd9d1e.png">

**Highlighting is correct for Fira Code, and incorrect for MonoLisa.** Note interpolation on line 20 in these examples for a good comparison. (I've checked it in VS Code, too, with the same results — renders correctly with Fira Code, incorrectly with MonoLisa.)

**Comment by bebraw** [comment] 2022-05-06 07:32
Related to #142.

**Comment by bebraw** [comment] 2022-05-06 08:35
I opened a related issue at https://github.com/microsoft/vscode/issues/148885 to capture feedback from VS Code side.

**Comment by bebraw** [comment] 2022-08-20 04:02
The issue has been fixed at 2.0 prerelease by dropping the combination. It turns out it's a `wontfix` issue at VS Code anyway so that's likely the best solution.

**Comment by okonet** [comment] 2023-01-27 09:46
We identified the root cause of this issue and working on the proper fix.

**Comment by bebraw** [comment] 2023-02-15 17:17
This has been done in 2.004.

**Closed by bebraw** 2023-02-15 17:17 UTC
Labels: bug
