### ISSUE TITLE
[Bug]: too much letter spacing

### ISSUE THREAD

**Issue by nonnapopoa** [MonoLisaFont/feedback#262] opened 2024-03-14 03:40 UTC
### Edition

Complete (Pro)

### What version are you using?

2.012

### What type of weights are you using?

Variable (customized)

### Operating system

MacOS Sonoma 14.4

### Program

WebStorm

### Display resolution

1496x976

### What happened?

The IDE font size is 15 with the line height of 1.2. Check the letter spacing for JetBrains Mono and MonoLisa font.

![CleanShot 2024-03-13 at 23 45 43](https://github.com/MonoLisaFont/feedback/assets/150189680/1ed98b8b-527c-4065-a55e-232f207d36c8)

**Comment by bebraw** [comment] 2024-03-14 05:08
This might be a duplicate of #218 as the font is wider by default than many other to give more space for letters like "m".

**Comment by bebraw** [comment] 2024-03-15 08:18
We discussed the issue and currently MonoLisa is a bit wider by design. You should follow #218 as it's a related issue.

**Closed as completed by bebraw** 2024-03-15 08:18 UTC
Labels: bug
