### ISSUE TITLE
Typo in pricing in monalisa.dev

### ISSUE THREAD

**Issue by anasansari157** [MonoLisaFont/feedback#29] opened 2020-05-20 06:50 UTC
On monalisa.dev, the pricing format is incorrect for INR (Indian currency).

**Comment by bebraw** [comment] 2020-05-20 06:57
Can you provide more info? Which browser are you using? What should the formatting be like?

Currently we rely on the browser APIs for handling formatting.

**Comment by anasansari157** [comment] 2020-05-20 09:36
I am accessing [this url](monolisa.dev/buy) from Chrome 81 on Linux. The price shows like this: Rs 2.999,00 ([link to the image](https://freeimage.host/i/JMpK5G)) but it should be like Rs 2,999.00.

**Comment by bebraw** [comment] 2020-05-20 09:42
Hi,

Looks like it's coming from this:

<img width="258" alt="Screenshot 2020-05-20 at 12 41 32" src="https://user-images.githubusercontent.com/166921/82431444-4f560c80-9a97-11ea-9029-84c34c38aff8.png">

Here's the code in an easier to copy format:

```js
new Intl.NumberFormat('in', {
                style: "currency",
                currency: 'inr'
              }).format(2999)
```

The next question is, why is the standard behavior wrong and how to fix it?

**Comment by anasansari157** [comment] 2020-05-20 09:53
@bebraw The problem is in defining the first argument in `Intl.NumberFormat`. Instead of using 'in', 'en-IN' solves the problem.

This works perfectly as you'd want it:
```javascript
new Intl.NumberFormat('en-IN', {
                style: "currency",
                currency: 'inr'
              }).format(2999)
```

**Comment by bebraw** [comment] 2020-05-20 10:00
@anasansari157 Ok, makes sense. I think I'll need to add some logic to map specifically to `en-IN` so it renders correctly. Thanks!

**Comment by anasansari157** [comment] 2020-05-20 10:08
You're welcome, @bebraw. Happy to help. 

Have a nice day!!
P.S. It was really hard to find the repo related to the website where I can suggest the changes.

**Comment by bebraw** [comment] 2020-05-20 10:10
@anasansari157 I think I'll add a feedback link to the footer. Good call. :)

**Comment by bebraw** [comment] 2020-05-20 10:33
@anasansari157 Can you check https://www.monolisa.dev/buy now? I added a small transformation to `en-IN` but I don't have an easy way to validate this as the solution resolving country is IP based.

There's a feedback link at the footer (just made sure). Any ideas how to do that better?

**Comment by anasansari157** [comment] 2020-05-20 11:01
@bebraw The error persists.
It is still showing like this:
[Price tags](https://i.imgur.com/qwisyVs.png).
However, if I click on it to purchase, it shows the correct pricing like this:
[Purchase link](https://i.imgur.com/hIOlzy2.png?1)
I think prices in both the images are using different APIs. Is it like that?

Yes, the footer is there in the right place. I checked it just now.

**Comment by bebraw** [comment] 2020-05-20 11:13
@anasansari157 It's a little different, yeah. The problem is that I don't know what Paddle is returning as a country for India so I made a guess on that and it wasn't correct.

I think I'll have to try to look at it from another angle and see what they return in order to patch the behavior.

**Comment by bebraw** [comment] 2020-05-20 11:16
I see now. They are returning `IN` for the country so I'll have to map against that.

**Comment by bebraw** [comment] 2020-05-20 11:20
@anasansari157 I applied the `IN` fix. Fingers crossed. Give it a go. :)

**Comment by anasansari157** [comment] 2020-05-20 11:22
Hey, @bebraw . You did it!!!
It works like a charm :)

**Comment by bebraw** [comment] 2020-05-20 11:22
Perfect. 👍

**Closed by bebraw** 2020-05-20 11:22 UTC
