### ISSUE TITLE
Excessive padding-bottom on Webstorm UI

### ISSUE THREAD

**Issue by calebeaires** [MonoLisaFont/feedback#33] opened 2020-06-29 22:04 UTC
While using Webstorm, inside editor, terminal and inputs the font goes very well, but on the Webstorm interface UI it is not. Se the image below. With others fonts (JetBrains, SourceCode... etc) it is ok.

<img width="1099" alt="Screen Shot 2020-06-29 at 18 57 28" src="https://user-images.githubusercontent.com/794195/86060513-38fa8380-ba3b-11ea-8b25-6eacc9f3d6ef.png">

**Comment by okonet** [comment] 2020-06-30 05:57
We are aware of this and working on the fix currently. It will be released very soon. 

Duplicate of #26

**Comment by calebeaires** [comment] 2020-06-30 13:28
Cool!
How do I follow the updates. Does the update comes by email to purchased ones?

**Comment by bebraw** [comment] 2020-06-30 13:54
@calebeaires If you've subscribed to the updates when buying, you'll get email. Also [@facetype](https://twitter.com/facetype) will announce new releases through Twitter.

**Comment by bebraw** [comment] 2020-07-02 14:52
Duplicate of #5. The issue should be fixed now.

**Closed by bebraw** 2020-07-02 14:52 UTC
