### ISSUE TITLE
Regular looking Bold in VS Code

### ISSUE THREAD

**Issue by MarcusSterz** [MonoLisaFont/feedback#31] opened 2020-06-16 12:26 UTC
Apparently for some user Regular looksBold in VS Code 
![image](https://user-images.githubusercontent.com/51958720/84773851-4cd6cc00-afdd-11ea-9d03-684f3234d44f.png)
![image](https://user-images.githubusercontent.com/51958720/84773861-506a5300-afdd-11ea-9829-f43a6f60c247.png)
![image](https://user-images.githubusercontent.com/51958720/84773872-52ccad00-afdd-11ea-9623-af4657af7b3a.png)
![image](https://user-images.githubusercontent.com/51958720/84773879-55c79d80-afdd-11ea-91a0-b98dd29cd081.png)

**Comment by bebraw** [comment] 2020-06-16 13:18
Here's render from my system when using the newest distribution version (1.401, personal edition):

<img width="898" alt="Screenshot 2020-06-16 at 16 16 56" src="https://user-images.githubusercontent.com/166921/84779281-e063c900-afec-11ea-90f6-f90f2d702a9f.png">

I'm using MacOS.

Do you know the operating system of the reporter? Is the behavior the same with other editors?

**Comment by MarcusSterz** [comment] 2020-06-16 13:24
> Do you know the operating system of the reporter? Is the behavior the same with other editors?

No, he insists on being serviced via email ...(forwarded to you)

**Comment by bebraw** [comment] 2020-06-16 13:30
Ok, looks like it's a Mac.

I would say let's keep this open to see if anyone else can reproduce the issue.

**Comment by nloding** [comment] 2020-08-19 15:03
I am experiencing the same issue, with VS Code on Windows 10. It occurs regardless of the theme I'm using, font size, etc. I've also explicitly set VS Code to use "MonoLisa Regular" and the weight doesn't change. There is a slight but visible change if I increase the font weight to 700+, but the "normal" weight is definitely not rendered correctly.

**Comment by bebraw** [comment] 2020-08-20 14:53
@nloding Can you do a couple of screenshots?

Here's mine on MonoLisa/MonoLisa-Regular on MacOS with VS Code:

<img width="199" alt="Screenshot 2020-08-20 at 16 51 33" src="https://user-images.githubusercontent.com/166921/90787900-e5573880-e30d-11ea-8989-97b6157b0f4f.png">

I wonder if there's something system specific we're missing.

**Comment by nloding** [comment] 2020-08-20 15:07
@bebraw here's a screenshot of the same text as the samples above. Maybe it's just my eyes and not being used to a wider font (coming from Dank Mono) but it just seems heavier in VS Code (regardless of theme) than it does when I view the MonoLisa website or screenshots from other users.

![monolisa-sample2](https://user-images.githubusercontent.com/328425/90789561-94881580-e2f6-11ea-8fcb-3ef354dc6cae.png)

![monolisa-sample1](https://user-images.githubusercontent.com/328425/90788921-d1074180-e2f5-11ea-84ec-038fc07afb2a.png)

**Comment by bebraw** [comment] 2020-08-20 15:32
@nloding I think I see what's up. My render was with `fontSize` set to 12.

Here's a comparison with `fontSize` set to 16:

<img width="325" alt="Screenshot 2020-08-20 at 17 30 11" src="https://user-images.githubusercontent.com/166921/90792601-551bf200-e313-11ea-88f7-87e3ae56004e.png">

Below with `MonoLisa-Light`:

<img width="294" alt="Screenshot 2020-08-20 at 17 30 20" src="https://user-images.githubusercontent.com/166921/90792621-5baa6980-e313-11ea-9977-cc3be6efaf7e.png">

It definitely feels like the font behaves better when it's set lighter on larger font sizes.

@MarcusSterz Do you have any thoughts on this scaling issue?

**Comment by nloding** [comment] 2020-08-20 15:55
@bebraw unfortunately 12 is too small on my monitor, and the Thin variant isn't available in the personal edition :(

**Comment by bebraw** [comment] 2020-08-20 15:59
@nloding Yeah, let's wait for some feedback from the designer. Ideally we would be able to provide weights one by one to cover these kind of cases. 😄

**Comment by nloding** [comment] 2020-11-04 00:46
Wanted to follow up on this. I've gotten used to the bold look, but don't want to give up! :)

**Comment by bebraw** [comment] 2020-12-04 12:23
@nloding We've set up a Plus package that includes more weights. Send me email if you haven't received it as our earlier customer and I'll make sure you have access.

I wonder if we should close this issue now.

**Comment by okonet** [comment] 2020-12-06 11:21
I wonder if it's related to https://github.com/MonoLisaFont/feedback/issues/42

**Comment by okonet** [comment] 2020-12-06 11:22
How did you install the font? What font files did you use to install?

**Comment by bebraw** [comment] 2021-02-18 10:41
@nloding Can you download the recent 1.603 and try now? We've fixed #42 so that the names should work as you expect on that platform.

**Comment by nloding** [comment] 2021-02-18 19:01
@bebraw it looks _much_ better now, pretty much how I expect it to. Thank you!

**Comment by bebraw** [comment] 2021-02-19 05:36
I think I finally understand what happened here. The original reporter must have been using a TTF under MacOS (I assume it works) instead of OTF (which I did). That explains why I didn't see the difference in the first place.

Now that the font name has been fixed in TTF, I don't think we'll encounter this one again even if someone accidentally uses TTF over OTF under MacOS.

**Closed by bebraw** 2021-02-19 05:36 UTC
