### ISSUE TITLE
Ligatures in intellij idea appear distorted.

### ISSUE THREAD

**Issue by eduardo-valenzuela** [MonoLisaFont/feedback#14] opened 2020-03-16 04:33 UTC
Ligatures like the triple equal appear distorted in intellij idea, the editor shows a thick line at the top and two thin lines at the bottom instead of showing them with equal thickness.

**Comment by okonet** [comment] 2020-03-16 06:57
Please provide a screenshots and versions of OS and Idea.

**Comment by mattdkerr** [comment] 2020-04-20 17:39
duplicate of issue https://github.com/MonoLisaFont/feedback/issues/19

**Comment by bebraw** [comment] 2020-05-05 16:25
Let's close as duplicate of #19 (assuming it's Windows).

**Closed by bebraw** 2020-05-05 16:25 UTC
